### ISSUE TITLE
Infinite Scrolling - UI experience

### ISSUE THREAD

**Issue by chandmk** [continuousit/seq-releases#129]
In out test a faulty component was throwing errors which caused it to log thousands of identical errors.  We are trying to understand when this issue exactly started.  

Infinite scrolling is tiring to get to the starting point of the issue. A feature that allows to quickly page through the data (jump to certain number of record) should be super useful.

**Comment by nblumhardt** [comment]
Moved to: https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976207-accelerated-scrolling

Thanks!
