### ISSUE TITLE
Hiding the events from the view

### ISSUE THREAD

**Issue by chandmk** [continuousit/seq-releases#130]
A fatal issue occurred due to infrastructure failure.
That causes large number of events.
Now the infrastructure issue is fixed.  
Those large number of events are not useful anymore. 
They are a distraction to get to the older but useful events.

It will be nice to be able to hide a block of events from the view.

**Comment by nblumhardt** [comment]
Moved to: https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976202-provide-a-way-to-suppress-but-not-delete-events

Thanks!
