### ISSUE TITLE
Disable manual trigger of Seq app

### ISSUE THREAD

**Issue by jansson** [continuousit/seq-releases#157]
As we add more app instances to Seq, we find the "Send to app" button on events less and less useful. We only use it for a handful of apps, and for the other, manually triggering events is actually harmful.

A setting to disable manual trigger, or automatically disable manual trigger when listening on a view/query would be nice.

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/14128033/414e4e3e-f660-11e5-84d7-2039334145fd.png)

Done.
