### ISSUE TITLE
Easier toggling between existing filters and views

### ISSUE THREAD

**Issue by slimflem** [continuousit/seq-releases#18]
For pure convenience, it would be very handy to have existing filters and views accessible while one is active.  You could possibly make the existing UI that indicates the active filter/view to be a drop down listing the existing ones.

![image](https://f.cloud.github.com/assets/886340/1699727/2fc893aa-5fbc-11e3-847d-1c4f323ff493.png)

**Comment by nblumhardt** [comment]
In 2.0.
