### ISSUE TITLE
Render html links as links

### ISSUE THREAD

**Issue by andrewtobin** [continuousit/seq-releases#184]
Hey Nick,

We have some internal web apps we can look up issues/products - I was just thinking if when we have an issue with a particular item we can render a link to that page so that we can quickly navigate and investigate it'd be helpful.  So I set that up and it rendered as plain text.  I think a regex or something to render out anything generated as a url, as a clickable url would be good.

Thanks

![seq-httplinks](https://cloud.githubusercontent.com/assets/520748/3946336/c48d5ffe-266b-11e4-8086-0c01bf050588.PNG)

**Comment by nblumhardt** [comment]
Moved to: https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976159-pluggable-extended-visualization-of-property-data - thanks!
