### ISSUE TITLE
Make it easier to copy message text

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#196]
Clicking the message text opens the event detail view, preventing copy/paste. Similarly when the detail view is open, clicking the message text causes the detail view to close.

When the detail view is open, let's provide a close `x` button separate from the message text so that copy/paste operations are easier.

**Comment by nblumhardt** [comment]
I've implemented the close button approach, but it feels itself like a severe ergonomic regression - to collapse a large event it's necessary to move the mouse a long way, to a small target.

![image](https://cloud.githubusercontent.com/assets/342712/5670861/7e4b3a04-97cf-11e4-8e95-610465f55c43.png)

Back to the drawing board I think. Perhaps making the button pin the event "open" rather than closing it, would be a better design.

**Comment by arri-cc** [comment]
@nblumhardt a pin would be cool. The key goal having an easy way to copy the text.  In youtrack, when an issue is open .  Would be cool if something like that were available.

Issue collapsed:
![image](https://cloud.githubusercontent.com/assets/1765960/5671475/3d03c7ba-9756-11e4-8e0a-4dfd7fb9492b.png)

Issue expanded in list:
![image](https://cloud.githubusercontent.com/assets/1765960/5671496/60511664-9756-11e4-91c7-debe844db254.png)

Copy icon that appears when hovering over certain fields while open:
![image](https://cloud.githubusercontent.com/assets/1765960/5671514/7dfacaca-9756-11e4-90bb-58796650ed04.png)

**Comment by nblumhardt** [comment]
Fixed! :)

**Comment by arri-cc** [comment]
awesome!
