### ISSUE TITLE
As a user I want to group views into meaningful categories

### ISSUE THREAD

**Issue by gkinsman** [continuousit/seq-releases#200]
Currently, the only way I can list views is this:

![image](https://cloud.githubusercontent.com/assets/130231/4246066/65d1f38e-3a44-11e4-9e23-9f0d42f7dea7.png)

I'd like to be able to do this:

![image](https://cloud.githubusercontent.com/assets/130231/4246150/e016a3d2-3a45-11e4-99e8-84cb7e15be0e.png)

The use case is pretty clear I think - I want to have views for particular environments, but for the purpose of retention policies and views that don't really fit anywhere I want to group them.

There might be a more general feature here, in which I could create composite views that might appear in a similar hierarchy. For example, I want to view all of the errors in production - I'd have a Production category (which would show all the prod events), and then an Errors sub category which would show the errors filtered to production.

**Comment by nblumhardt** [comment]
Hi @gkinsman - The layout and optional display of signals in v2 should have improved the situation a lot. How's it going?

**Comment by gkinsman** [comment]
Hi Nick, loving the new signals interface. I'd consider this one resolved :)

**Comment by nblumhardt** [comment]
Thanks!
