### ISSUE TITLE
Support Google Reader-esque J and K key navigation

### ISSUE THREAD

**Issue by bytenik** [continuousit/seq-releases#22]
When looking at a log event, support pushing J to move to the next log event (i.e. collapse the current one, expand the next one) and K to move back to the previous.

**Comment by nblumhardt** [comment]
Working to get the tracker into a tidier state; this is a cool idea - for now it's living at: https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976122-support-google-reader-esque-j-and-k-key-navigation

Thanks!
