### ISSUE TITLE
Allow to select time in the DatePicker

### ISSUE THREAD

**Issue by sebwerner** [continuousit/seq-releases#226]
Hi, 
the DatePicker on seq is a great way to navigate to the logs of a specific day. 
It would be great if i could further narrow it down by selecting the time span i need as well. 

Thanks

**Comment by IanYates** [comment]
:100:

**Comment by nblumhardt** [comment]
Coming in 2.0....

**Comment by nblumhardt** [comment]
Time selection is in the beta; some kind of picker will follow.

**Comment by IanYates** [comment]
:grinning:
