### ISSUE TITLE
Visual notification of new update to Seq

### ISSUE THREAD

**Issue by andrewtobin** [continuousit/seq-releases#229]
It would be nice if in the footer where the release number was, there was some representation on if there is a new update available, with a setting in the main setup if pre-releases should be shown.

It could probably be done from the same feed that does the download page on getseq?

**Comment by redwards510** [comment]
Looks like it already does this. At the bottom of my Seq in the footer there is:
Seq 1.6.11 — Copyright © 2013-2015 Continuous IT Pty Ltd — License — **Get Seq 1.6.12**

The Get Seq 1.6.12 link takes you to the download page.

**Comment by nblumhardt** [comment]
Absolutely - thanks Ryan :)
