### ISSUE TITLE
Private (per-user, shared-as-readonly) queries and views

### ISSUE THREAD

**Issue by Jaben** [continuousit/seq-releases#232]
Hey Nick.

Right now we all use pretty much the same admin account, which works fine except one thing: Some views are special view for data retention polices, thresholds, dashes, etc.

The problem is that people go in an accidentally (or not) delete, modify, and generally break these important views. It would really be helpful to be able to create views that can 1. be locked and hard to modify. 2. treated as "system" views that are shared and are always available with a toggle to "hide" them.

Also a way to export/import these views (ala  #166) would be smashing. :)

**Comment by nblumhardt** [comment]
Here's where we're at:

![image](https://cloud.githubusercontent.com/assets/342712/7466063/188916c6-f320-11e4-87b1-793890863067.png)

The list in the dialog shows everthing; the list in the blue sidebar you can see to the right only includes the items the user has explicitly opted into.

It's a lot harder to inadvertently modify a shared query/view in Seq 2; I don't think we'll go as far as "locking" in this iteration, but hopefully the core of the scenario's now satisfied. What do you think?

**Comment by Jaben** [comment]
I think it looks like a great improvement! I like the concept of "Signals". They completely replace the query/view, correct?

If not locking, maybe if app has a Signal selected, it could show as "in use by [list of app(s)]" in the dialog?

A Clone Signal option would be very helpful when you want to slightly modify an existing Signal.

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/7526665/0af0149a-f557-11e4-9637-8246bbbf0695.png)

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/7526810/98b23564-f558-11e4-935e-0c33df9ee338.png)

Not perfect, but improves on the status quo - might leave it at this point for now. Cheers!

**Comment by Jaben** [comment]
:+1: great, mate!
