### ISSUE TITLE
Manually create API Key

### ISSUE THREAD

**Issue by richardlawley** [continuousit/seq-releases#242]
I would like to be able to create an API key manually, i.e. not have it auto-generated.  I would expect the default to be to auto-generate a key, but it would be useful to be able to override this and specify your own.  I would be using this to keep the key constant between development and production environments, as I define the server centrally.

**Comment by nblumhardt** [comment]
Thanks - that makes sense. I've moved this over to UserVoice as [a suggestion](https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976097-allow-api-key-tokens-to-be-specified-explicitly), since it's not on our very-near-term roadmap, but I'll keep it in mind.

Regards,
Nick

**Comment by nblumhardt** [comment]
This shipped as #367.
