### ISSUE TITLE
Filter on properties containing white space or other characters

### ISSUE THREAD

**Issue by jansson** [continuousit/seq-releases#252]
I can't seem to filter on properties whose names contains white space or for example dash. Is there some special syntax required or is it not supported?

**Comment by nblumhardt** [comment]
Hi Kristoffer - no, non-C#-style property names aren't supported in the query syntax currently. We could add support, but ultimately I think life will be easier without them. Are they just coming in via `ForContext()` statements? Thanks!

**Comment by jansson** [comment]
Yeah that's right. I could easily switch them out.

**Comment by nblumhardt** [comment]
Not expecting we'll address this in the near future; closing for the time being. Thanks!
