### ISSUE TITLE
Seq shows 'true' for System.Boolean true but empty string for false

### ISSUE THREAD

**Issue by gkinsman** [continuousit/seq-releases#253]
Upon doing 

`Log.Error("True: {ATrueValue}, False: {AFalseValue}", true, false);` 

from serilog, seq shows "true" for ATrueValue but empty string for AFalseValue in the property view.

![](http://i.imgur.com/0ZR7g0A.png)

**Comment by nblumhardt** [comment]
Hi George!

Which version of Seq are you using, and which browser? I'm running 1.6.8 and tested in IE, FF and Chrome, and get this:

![image](https://cloud.githubusercontent.com/assets/342712/5753996/0550795c-9cde-11e4-8cb2-52ca21edeb23.png)

Thanks!

**Comment by gkinsman** [comment]
Ah, sorry about that Nick. I'd updated our instance on the build server but not my local. I believe I was using 1.4.x. Just updated and all is well. Thanks!
