### ISSUE TITLE
Automatic online compaction not respecting seq storage setting

### ISSUE THREAD

**Issue by caseymarcallen** [continuousit/seq-releases#259]
When Seq is doing its automatic esent compaction it is using temp files in the C:\Windows\System32 folder. 

This online compaction should respect the storage path settings which have moved all Seq data over to a different (large) drive. Our C: drive on the server does not have enough storage space to be able to handle the large temporary file that is being created and the server is eventually running out of disc space.

I can manually compact by using a console window and running seq compact while executing from a working directory on my large drive, but the automatic online process doesn't do this.

**Comment by nblumhardt** [comment]
Thanks Casey, I'll take a look

**Comment by nblumhardt** [comment]
Fixed, need to be run for a while to re-test so bucketing this with 2.x; if the workaround is causing you pain @caseymarcallen  let me know and I'll send a patched 1.6. Thanks for the report!

**Comment by caseymarcallen** [comment]
Any idea on the timeline for the 2.0 release? 

The manual compaction didn't actually seem to reduce the size of the extants at all even after running for an hour or so and saying it was all processed. So it feels like a bit of a time bomb at the moment just waiting to see if it takes down the c: drive when it does an auto compaction.

The alternative for me is to manually delete all events and start fresh, but does deleting events immediately drop the size of the extant and eliminate the compaction problem or do I need to do something else?

**Comment by nblumhardt** [comment]
The plan for 2.0 currently is "midyear" but that may vary quite a bit; it sounds like a 1.6.x is going to be the best solution for you. I'll reopen this and back-port it shortly.

Compaction will only free space if it can; i.e. if the retention policies have run and freed up some space in the files - it may be that there's some other factor to consider.

Can you possibly check the sizes of the various extent folders? I.e. is the most recent one largest, and the others getting smaller as they go back in time?

Will follow up when there's a build available; thanks for the extra info!

**Comment by nblumhardt** [comment]
1.6.12 is building now...

**Comment by nblumhardt** [comment]
1.6.12 is up, please let me know if you have any further trouble with it. Cheers!

**Comment by caseymarcallen** [comment]
I updated to the 1.6.12 version, but the problem still re-occured. The 28GB temp defrag files were still created in C:\Windows\System32 which filled the C: drive and brought the server to its knees. I have the seq windows service configured with to run with:

    "C:\Program Files\Seq\seq.exe" run --storage="E:\SeqData" --listen="http://logs/" --ram-target="20"

Whereby the storage path is set to E: drive.

Any thoughts on what's going wrong here?

**Comment by nblumhardt** [comment]
Hmm that's not good, let me take another look. Thanks for the heads-up!

**Comment by nblumhardt** [comment]
Very sorry to report this - there was a build issue preventing the fix from being included in 1.6.12.

1.6.13 includes the fix (really, this time!) and will be on the site in a few minutes.

Thanks for following up with this, much appreciated.

**Comment by caseymarcallen** [comment]
Excellent, thankyou! 

I had to disable seq in production for the last month, so this is great to get it up and running again.
