### ISSUE TITLE
Better handling of large data amounts

### ISSUE THREAD

**Issue by BlueWombat** [continuousit/seq-releases#261]
I would propose that handling of larger amounts of data, both big payloads and large amounts of entries are better handled. Possibly ditching the current self-made Json datastore and switching to Redis, MongoDB, CouchDB or whatever.

Currently querying takes quite a long time, similarly deleting is a very long running task too, as I suspect it deserializes every single Json payload during delete, to figure out whether it's supposed to be deleted or not.

I would happily contribute to this transition.

**Comment by nblumhardt** [comment]
Hi Mikkel,

Thanks for the note - how much data are you storing, and on what hardware? If you can send a snapshot of _Settings > Metrics_ that might help narrow it down.

As log stores, MongoDB, CouchDB and Redis all have limitations of their own - Seq's by far the youngest of that set, with some pretty huge perf gains still being had between versions. We'll get there! :-)

**Comment by nblumhardt** [comment]
Hi again - just looping back on this one. If you need a hand with setup please drop support@ a line! Closing this for the time being. Cheers!
