### ISSUE TITLE
Please format the JSON in seq's api

### ISSUE THREAD

**Issue by gkinsman** [continuousit/seq-releases#262]
Is it possible to please have the JSON at http://sequrl/api formatted? It would make the output nice to navigate without the need for browser plugins.

Thanks!

**Comment by nblumhardt** [comment]
Thanks for the note - will look into this.

**Comment by nblumhardt** [comment]
Currently for space reasons it seems the status quo, and e.g. using the response view in Chrome dev tools, is the way to go here. Thanks for the input!
