### ISSUE TITLE
[Enhancement] - Minimize Signal Bar

### ISSUE THREAD

**Issue by BrendanThompson** [continuousit/seq-releases#277]
It would be good to be able to minimize the `Signal Bar`, as it can take up a bit of screen real estate

**Comment by nblumhardt** [comment]
Thanks BT - looking into this :+1:

**Comment by BrendanThompson** [comment]
Now __that's__ service!

**Comment by nblumhardt** [comment]
I've been experimenting with sizing some more; there are some challenges around collapsing it (making sure the user still has a good indicator what filters are active) that means this ticket will probably have to wait until post-1.0.

Dropping the proportion of screen space taken my it seems to be an improvement:

![image](https://cloud.githubusercontent.com/assets/342712/7926283/9765a244-0913-11e5-9913-48a8e23de95e.png)

Will be keen for your feedback on the next beta :-)

**Comment by BrendanThompson** [comment]
What you could do is if the Signal Pane gets minimized (collapsed) then the active filter is shown as a field inline with the query bar using the same blue background as the Signal Pane. Also, in that title section is where you'd have the `>>` indicating collapsing and `<<` for expansion.

That all make sense?

**Comment by nblumhardt** [comment]
Yup! Thanks Brendan!

**Comment by nblumhardt** [comment]
Hey Brendan! Hope you're enjoying V2 :-)

This is a good suggestion but won't be on the cards in the immediate future, so I've moved it to our UserVoice site to keep the issue tracker orderly: http://seq.uservoice.com/forums/268188-general/suggestions/8952403-allow-minimizing-the-signal-bar

Cheers!

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/13417722/2b95fef0-dfba-11e5-8963-97cc5fa9d69a.png)

Done; will be in the next preview release for Seq 3.
