### ISSUE TITLE
Hovering a tag shows "tag.name" as a tooltip

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#290]
![seq-tag-tooltip](https://cloud.githubusercontent.com/assets/160544/7954550/bada5ce8-09d0-11e5-8a36-a9da483d9c4b.png)
When a tag is created, hovering over the tag in the event list show the text "tag.name". 
I would expect to find here either : 
- a tag description
- the underlying property name
- a hint of what is going to happen if I click on the tag
- something else ?

(as of Seq 2.0.13-pre)

**Comment by nblumhardt** [comment]
Thank you; fixed.
