### ISSUE TITLE
Allow ordering of tags

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#291]
Right now, when adding a tag, I think it is added to the right of existing tags.
Some times, there is some sort of hierarchy in that tags, and we would want them to appear in a specific order, for instance : 
1. serverName
2. appName
3. appComponent
4. appVersion

So it would be nice if we could specify in which order those tags appear in the event list 
![seq-tags](https://cloud.githubusercontent.com/assets/160544/7954627/7ae8e554-09d1-11e5-935e-c25dafd33553.png)

**Comment by nblumhardt** [comment]
Thanks again for the idea; moved this to our UserVoice site at: http://seq.uservoice.com/forums/268188-general/suggestions/8952367-allow-ordering-of-signals
