### ISSUE TITLE
Adding tags independently from signals

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#292]
I know it's just a beta so far, but I find the "tagging" functionality a bit confusing.

I have the feeling tags stored as part of the signals ? I guess it makes sense to mark some properties as tag only in the context of a filtered list of events, but there are some tags we would want to see on all events, even when "no signal" is currently selected.

So I suppose I'm requesting "global tags", that would for instance be saved when I add tags, having selected no signal yet in the right panel.

(as of Seq v2.0.13-pre)

**Comment by nblumhardt** [comment]
Thanks again for the suggestion; moved this to: http://seq.uservoice.com/forums/268188-general/suggestions/8952343-configure-tags-independently-from-signals

**Comment by tsimbalar** [comment]
FWIW : this functionality is now covered with the #379 because I can set as default signal a signal that contains tags.

**Comment by nblumhardt** [comment]
Awesome, thanks for the note @tsimbalar.
