### ISSUE TITLE
Include tags in charts on dashboard

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#293]
It would be nice if the properties marked as tags would be taken into account in the charts on the dashboard.

I would expect the generation of a stacked history chart, with sub values for each value of the property

![seq-charts-accumulated](https://cloud.githubusercontent.com/assets/160544/7954817/239d8f6e-09d3-11e5-8560-12685c1031dc.png)

as of Seq v2.0.13-pre

**Comment by nblumhardt** [comment]
Thanks for all the suggestions!

**Comment by nblumhardt** [comment]
To make the issue tracker easier to manage I've moved this to our UserVoice site: http://seq.uservoice.com/forums/268188-general/suggestions/8952319-stack-dashboard-charts-by-tagged-property

Thanks again for the suggestion!
