### ISSUE TITLE
Dashboard counter keeps on growing

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#296]
After doing some "load testing" (i.e. sending a million events to Seq from SeriLog), I noticed a strange behaviour on a Dashboard I have designed using an empty filter. 
Note that not more events were being sent when I noticed the glitch.

The little badge used to indicate around 600,000 events. After clicking the badge, I get to the list of events ... but if I then go back to the dashboard, the counter is back to a low number ... but if I keep on refreshing the page, this number increases and increases ....
After I click, it's reset to zero, but keeps on increasing again.

It may be the expected behaviour of how events are processed for dashboards, but I'm not that sure :)

(as of Seq v2.0.13-pre)

- just after clicking the event number, and navigating back to the dashboard, I already have some messages
![seq-dash-1](https://cloud.githubusercontent.com/assets/160544/7962588/777e7388-0a0e-11e5-9fc2-a8e5e1909ed3.png)

- if I wait for some time, the number keeps on increasing ...
![seq-dash-2](https://cloud.githubusercontent.com/assets/160544/7962601/8a5314d2-0a0e-11e5-98aa-27fd6c3ada2d.png)

- ... but I did not get any new messages in the event list (see date of last event)
![seq-dash-3](https://cloud.githubusercontent.com/assets/160544/7962620/a06d615a-0a0e-11e5-8868-88e2766d48e3.png)

**Comment by nblumhardt** [comment]
Thanks - that's interesting, will see what I can figure out...

**Comment by nblumhardt** [comment]
Hi @tsimbalar - did this stabilise? Building the initial value may sometimes take a little time, but I haven't repro'd the unbounded growth. Any further clues? Cheers!

**Comment by tsimbalar** [comment]
@nblumhardt  My computer restarted so I kind of lost it :-/
I'll try again with the latest version of Seq. 
Thanks !

**Comment by nblumhardt** [comment]
Thanks @tsimbalar - I'll close this for now but feel free to reopen if you see this again. Cheers!
