### ISSUE TITLE
charting : evolution of numerical value over time

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#299]
Right now, the dashboards allow to show the total number of messages passing a filter on a given time range. 

Something I would like to see is the possibility of **graphing the evolution of a numerical message property over time**.

For instance, if I store a message of the form
"Request took {Duration} ms"
I would want to generate a chart of the evolution of numerical value "Duration" taken from all the events that match this template (or another more specific filter).

I believe it would actually be doable accessing the REST API of seq...

More advanced things : 
- compute aggregates (Avg/min/max) of those values per hour / day / week etc and allow "zoomin/out" of time periods

**Comment by nblumhardt** [comment]
Would love to see this too! On the list, but hard to tell at this point when we'll give additional charting the focus. Definitely keeping it in mind! :-)

**Comment by andymac4182** [comment]
I know this is difficult but it would be great to graph Average and various percentiles of numeric values. I am using SerilogMetrics for a few counts and timers and it would be great to be able to see the average grow or shrink over time.

**Comment by nblumhardt** [comment]
```sql
select mean(RequestTime), percentile(RequestTime, 95) from stream group by time(7d)
```

...will do this in Seq 3. See: http://blog.getseq.net/sql-queries-in-seq-3-0-19-pre/

The charting aspect is still "TBD", but having aggregate/timeseries queries available paves the way for a lot more interesting scenarios :-)

Hope you'll check it out!

**Comment by tsimbalar** [comment]
That sounds promising ! I'll try and check that out :)

I believe it must be technically possible afterwards to build some charts on our own, consuming the Seq API, right ?

**Comment by tsimbalar** [comment]
I don't know whether or not to file an issue for that ... If logged a property of type `TimeSpan` , is there a way to use the value that is logged in such a query ? (I guess it would mean reparsing it ? )

Here's an example of a message where `Duration` is a TimeSpan:

```
{
  "Timestamp": "2016-02-17T08:49:32.2526258+01:00",
  "Properties": [
    {
      "Name": "HttpStatus",
      "Value": "OK"
    },
    {
      "Name": "HttpVerb",
      "Value": "GET"
    },
    {
      "Name": "ResourceUri",
      "Value": "https://localhost/whatever"
    },
    {
      "Name": "Duration",
      "Value": "00:00:00.0000894"
    },   
    {
      "Name": "SourceContext",
      "Value": "Foo.Bar.HttpHandlers.ClientActivityLoggerHandler"
    }
  ],
  "MessageTemplateTokens": [
    {
      "Text": "Response "
    },
    {
      "PropertyName": "HttpStatus"
    },
    {
      "Text": " to "
    },
    {
      "PropertyName": "HttpVerb"
    },
    {
      "Text": " "
    },
    {
      "PropertyName": "ResourceUri"
    },
    {
      "Text": " took "
    },
    {
      "PropertyName": "Duration"
    }
  ],
  "EventType": "$63D88CE9",
  "Level": "Debug",
  "Id": "event-df5a1a32376e08d309a5000000000000",
  "Links": {
    "Self": "api/events/event-df5a1a32376e08d309a5000000000000{?download,render}",
    "Group": "api/events/resources"
  }
}
```

**Comment by tsimbalar** [comment]
I actually just find out about the fonction `TotalMilliseconds(timespan)` which should do just that ... but the following does not work 

> An unhandled error occurred while serving the request (token: 6a2efe57e2ef4df7aac931917f7911c6).

`select mean(TotalMilliseconds(Duration)), percentile(TotalMilliseconds(Duration), 95) from stream group by time(7d)`

I would expect it to work, but maybe it's still at an early stage for that ? Should I open a new issue ? 
(I'm currently using Seq 3.0.19-pre)

**Comment by tsimbalar** [comment]
I could narrow it down : 

this works (*mean*):
`select mean(TotalMilliseconds(Duration)) from stream group by time(7d)`

this does not (*percentile*): 
`select percentile(TotalMilliseconds(Duration), 95) from stream group by time(7d)`

**Comment by nblumhardt** [comment]
Great! Thanks for spotting that, I'll take a look first thing Monday and let you know what I find :-)

**Comment by tsimbalar** [comment]
it works now with Seq 3.0.21-pre

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/14236326/d8ac928c-fa56-11e5-8ac3-fdcb222c9ca9.png)

Basics are coming in the 3.1 preview this week. Still many improvements possible but these can be raised/prioritised as individual tickets.

Also includes bar/pie charting, though timeseries is where the focus is going.
