### ISSUE TITLE
"Delete matching events" with no filter reports "0 events deleted"

### ISSUE THREAD

**Issue by c0ntinuum** [continuousit/seq-releases#305]
"Delete matching events" with no filter:

![action](https://cloud.githubusercontent.com/assets/515811/8323044/61ee225a-1a82-11e5-8205-a4170603d252.png)

Reports the following (in error):

![result](https://cloud.githubusercontent.com/assets/515811/8323046/7082d40a-1a82-11e5-9546-a56f8e49389b.png)

After F5 indeed all events have been deleted:

![afterf5](https://cloud.githubusercontent.com/assets/515811/8323058/99bd3b62-1a82-11e5-9124-7b3005387d6d.png)

Clearly a low severity / low priority defect (just letting you know) :+1:

**Comment by nblumhardt** [comment]
Thanks Tod, will check this one out.

**Comment by nblumhardt** [comment]
Fixed.
