### ISSUE TITLE
Consider enabling CORS to support client-side logging from JavaScript

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#310]
Raised here: http://docs.getseq.net/v2/discuss/558c7928b437fa2f004bc23a

Needs further investigation.

**Comment by nblumhardt** [comment]
Done.

**Comment by raybooysen** [comment]
Hi Nick

Maybe I'm being a bit slow, but maybe you can help. We are building a web application in Electron. Using seq and Bunyan seq, we are trying to log. However the post to seq is failing because our origin is localhost. Where can we set the CORS headers?

**Comment by nblumhardt** [comment]
Hi Ray - the `/api/events/raw` endpoint should accept all origins, though TBH I have no idea how Electron is set up in this case. Does it make sense in your scenario to disable CORS entirely? http://stackoverflow.com/questions/30101537/cross-domain-ajax-call-in-atom-shell

**Comment by raybooysen** [comment]
We'll investigate further.  The logging POST is happening on the main process, not the renderer so I don't have access to those options.

**Comment by raybooysen** [comment]
All sorted now.  @nblumhardt we do have one issue where if POSTs are failing, the onError handler is never called.  We need to test more and verify and will post an issue when we have that information
