### ISSUE TITLE
Option to enable auto-refresh by default

### ISSUE THREAD

**Issue by richardlawley** [continuousit/seq-releases#311]
A large amount of the time I use Seq, the first thing I do is hit auto-refresh.  It would be nice if this was a little easier, though I'm not sure what the best way would be, fitting in with other people's approaches.  Some possibilities:

* Remember the current auto-refresh setting, and restore it when the page loads (i.e. if you close the browser, when you open it again, auto-refresh will be on)
* Add a URL parameter for auto-refresh, so a bookmark can be stored with it enabled
* Add a user-level setting of whether auto-refresh should be enabled by default
* Provide a top-level button (so it's one click instead of two)

**Comment by nblumhardt** [comment]
Thanks Richard, I want to take a look at this as part of the next (2.2) release.

**Comment by nblumhardt** [comment]
In 2.2 we'll give this a try:

![image](https://cloud.githubusercontent.com/assets/342712/8514484/fd6b8e70-23d3-11e5-8514-70473f08c4e5.png)

New `-pre` build should be up today, great to have your feedback!

**Comment by IanYates** [comment]
I fetched the pre-release package just for this button :+1:

**Comment by nblumhardt** [comment]
Excellent :-)
