### ISSUE TITLE
Provide an easier way to work with/override partial result set paging

### ISSUE THREAD

**Issue by mneelakanta** [continuousit/seq-releases#317]
- When i try to access a particular number of records which also has a filter, the events returned seems to be getting capped.(only returns 39 events in this case no matter what the count is)

/api/events?count=10000&filter="Search text"

if i use it without any filter, it returns the correct number of events.

any ideas ?

**Comment by nblumhardt** [comment]
Hi Mouna,

In the response JSON, you'll see that `Statistics.Status` is `Partial`. To get the next batch, you need to then make another call with:

```http
GET /api/events?count=10000&filter="Search text"&afterId=<the last read id>
```

where `<the last read id>` is the `Statistics.LastReadEventId` value from the previous response.

This paging mechanism is a relic of how the UI works and probably shouldn't be carried through the rest of the API; I'll leave this ticket here as a reminder to clear it up.

Thanks for getting in touch, and let me if this doesn't help.

**Comment by nblumhardt** [comment]
BTW, this assumes you're using Seq 2.x - if you're on a 1.x server, the parameter is called `after`, not `afterId`.

**Comment by nblumhardt** [comment]
One option for us is to do this automatically in `SeqConnection.Events.ListAsync()` and friends in _Seq.Api.dll_, will consider that option.

https://github.com/continuousit/seq-api/blob/master/src/Seq.Api/Api/ResourceGroups/EventsResourceGroup.cs

@mneelakanta are you using C#?

**Comment by mneelakanta** [comment]
Thanks Nick.. That was really helpful. :) and yes i am using C#.

**Comment by nblumhardt** [comment]
Paging is now automatic in the API client's `ListAsync()`, which should improve usability in basic scenarios:  https://github.com/continuousit/seq-api#reading-events

For more complex ones, `InSignalAsync()` keeps the old behaviour.
