### ISSUE TITLE
Add eager loading of all / top N results

### ISSUE THREAD

**Issue by pawelpabich** [continuousit/seq-releases#327]
Hi,

I do a lot of queries where I want to see all events for a given version of my app in CI (e.g. version=="0.0.3.4" and I would like to be able to see results at once without having to scroll.

Thanks

Pawel

**Comment by nblumhardt** [comment]
Hi Pawel, thanks again for making a note of this.

The solution that seems to work best right now (as a trade-off between using server resources unnecessarily and improving scroll speed) is for Seq to bring back exponentially larger pages as the result set is scrolled. I.e. initially scrolling will feel the same, but the further the results are scrolled the larger the additional pages that will be retrieved and thus the less "jerkiness" will be experienced. It could still be tuned a little, but the difference seems noticeable with my test data set.

Should be out in a 2.3 preview in a day or so.

Cheers!
Nick

**Comment by pawelpabich** [comment]
Thanks, I will give it a try once released.
