### ISSUE TITLE
Allow administrative users to lock signals

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#337]
Via: http://docs.getseq.net/v2/discuss/55f2a450fb7aad2300bf17b7

**Comment by tsimbalar** [comment]
Actually there might be 2 levels : 
- private vs public signals : maybe I don't want my signals to be seen by other people
- editable vs read-only : maybe I don't mind if other people see my signals and their definition, but do not let them edit them (maybe allow to clone and edit ? )

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I decided to keep it simple in the first iteration, there's now a single per-signal setting that restricts access to administrators only:

![image](https://cloud.githubusercontent.com/assets/342712/10272104/ebf35ff2-6b5d-11e5-8e1a-51190ec8761e.png)

Should be out in preview within a few days.

Cheers!

**Comment by tsimbalar** [comment]
Great, that's a good start, thanks !
