### ISSUE TITLE
Payload size limit + durable log shipping issues tough to diagnose

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#339]
When Seq rejects an event, with durable log shipping enabled, the client retries _ad infinitum_ causing connectivity issues that are tough to debug.

This is by design, since durable log shipping both needs to prevent message loss, and make failures surface **somewhere**, but the specific failure mode here is tough to detect.

**Comment by miketrusov** [comment]
I suggest truncating overly long messages instead of just rejecting them. I had 2 clients generate 150mbits of traffic to a logging server because they kept trying to send multi-megabyte log entry batches.

Of course the problem is with content being logged, but I expect the framework to either truncate the message or throw rather than silently fail.

**Comment by miketrusov** [comment]
I suggest truncating and accepting overly long messages instead of rejecting them. I had 2 serilog clients generate 150mbits of traffic to seq server because they kept trying to send multi-megabyte log entry batches.

**Comment by lokki** [comment]
I second this, it would be great to have configurable payload limit not only on the Seq server, but on the Serilog clients as well

**Comment by nblumhardt** [comment]
The commit above addresses this by:

1. Dumping the payload to disk and moving on, if the Seq server responds with 400/413, from which the client can't normally recover, and,
2. Providing the `eventPayloadSizeLimit` to the `WriteTo.Seq()` configuration method to hopefully provide a way to avoid this situation occurring, at the expense of losing the larger events

The two are independent but can be used together to implement a few different behaviours around this. I'd recommend setting `eventPayloadSizeLimit` on the client to a reasonable value, and consider increasing the server-size payload limit once that change is rolled out.

The change will be in the `2.0.0-beta` series of the `Serilog.Sinks.Seq` package, which should allow for some time to iron out any kinks in this scheme.
