### ISSUE TITLE
EsentVersionStoreOutOfMemoryException under extreme write loads

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#341]
#208 increased the in-memory transaction buffer size to avoid `EsentVersionStoreOutOfMemoryException` under concurrent write loads, however it's still possible as of 2.3 to hit the new limit.

2.4 will boost this limit further for the most recent extent, but keep the lower limit for older extents not processing many writes, saving on some RAM use.

cc @sheastrickland

**Comment by nblumhardt** [comment]
Fixed

**Comment by sheastrickland** [comment]
Legend.
