### ISSUE TITLE
Can't add new user using Edge Browser

### ISSUE THREAD

**Issue by johnkattenhorn** [continuousit/seq-releases#343]
When adding a new user the password must match validation is broken in Edge, the view appears with this validation message already in place and not the user does can make it go away.

Works fine in IE though.

**Comment by nblumhardt** [comment]
Thanks for the report John, I'll take a look into this.

**Comment by nblumhardt** [comment]
Hi John,

Does this still occur for you in the latest Seq/latest Edge? I'm unable to replicate it as far as I can tell.

Thanks!
Nick

**Comment by johnkattenhorn** [comment]
Hey Nick,

Just tried this and the behaviour has changed and it's weird.

If I allow Edge to fill in previous remembered data it seems not to work unless you go back clear down the fields.

If you don't allow it to autofill form and type in the information manually then it works fine.

I saw your other tweet about Edge behaviour so maybe this in sort of in this camp too. It's workable though so we should close this issue.

Thanks

John
