### ISSUE TITLE
Impossible to toggle signal at the bottom of the page

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#346]
When the list of signals starts to grow a lot, signals get stuck behind the "Seq version / Copyright" information, and clicking no longer toggles the signal.
![seq-bottom-signal](https://cloud.githubusercontent.com/assets/160544/10606741/2dbc005a-7735-11e5-8389-e7b8cece1ee6.PNG)

You can reproduce the issue even with a small list of signals, by simply resizing the browser window.

In my case, this is Firefox 41.0.2 on Windows, connecting to Seq v2.3.4, and is still there on Seq v2.4.1-pre.

(reporting it here instead of forums, to be able to upload a screenshot)

**Comment by nblumhardt** [comment]
Thanks, will take a look at it.

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/10816580/862ebfce-7e7f-11e5-80f5-3992f38170a7.png)

Fixed in 2.4.2, due soon.
