### ISSUE TITLE
[Seq.Client.Portable] Doesn't work with localhost url and proxy

### ISSUE THREAD

**Issue by dazinator** [continuousit/seq-releases#348]
hello - thank you for this library: (https://github.com/continuousit/seq-client-portable)

I have my android device configured to use fiddler (running on my local development machine) as a proxy.

When using:

```csharp
               Log.Logger = new LoggerConfiguration()
               .WriteTo.SeqPortable("http://localhost:5341")
               .CreateLogger();

                Log.Information("Hello Log!");
```

The code runs fine (no exceptions) - but nothing comes through the Seq.

If I replace the above URL with IP Address - it works and things flow through to Seq.

I believe this might be a problem with the HTTP Client implementation being used and not respecting android system proxy settings.

I had a similar issue with RestSharp.Portable: https://github.com/FubarDevelopment/restsharp.portable/issues/45

RestSharp.Portable allows you to implementyour own httpclient factory, and this allowed me to configure it to use ModernHttpClient - which fixed the issue for me.

Perhaps we could allow a similar approach for this?

**Comment by dazinator** [comment]
PR Submitted

**Comment by nblumhardt** [comment]
Closed/fixed via your PR. Thanks!
