### ISSUE TITLE
Inner exceptions are not shown in the log

### ISSUE THREAD

**Issue by harvinders** [continuousit/seq-releases#351]
Whilst using serilog to log the exceptions, only exception message is shown. Sometime stacktrace is shown but never the innerexception.

It would be nice if innerexception(s) are also displayed in the logs

**Comment by nblumhardt** [comment]
Hi @harvinders - thanks for getting in touch!

Normally the inner exception message is formatted into the top line of the message, something like: "Message A -> Message B -> Message C", and the stack traces are concatenated into the one long stack trace. Is this what you're seeing?

Best regards,
Nick

**Comment by harvinders** [comment]
Hi, I am not seeing this. I am using seq to log using calls like

_log.Error(e.ContextError.Detail.Exception, "{Error} occured, {ErrorCode} : {ErrorMessage}", "TestSystemError", e.ContextError.Detail.ErrorCode, e.ContextError.Detail.Message);

Since you are saying that it should work, let me do some controlled experiments and get back to you.

Thanks
harvinder

**Comment by nblumhardt** [comment]
I'll close this for the time being, but please get in touch if you have any more trouble with this. Thanks!
