### ISSUE TITLE
Show week by hour as a dash time range option

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#353]

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/11133349/12e7b6a2-89e1-11e5-8508-5495508ca389.png)

**Comment by tsimbalar** [comment]
:+1:

**Comment by tsimbalar** [comment]
not really a show-stopper, but with so many time point, the x-axis becomes kind of unreadable :P

![seq-dash-week-by-hour](https://cloud.githubusercontent.com/assets/160544/13170410/096e5f88-d6ec-11e5-85e2-0ab996980bee.png)

**Comment by nblumhardt** [comment]
Thanks, I had that jotted down on a Post-it but think I missed getting an issue into the tracker here for it. Reopening!

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/13339965/3bb7ca2e-dc78-11e5-9eba-3b84e3287df6.png)
