### ISSUE TITLE
Suggestion: Display App NuGet Package ID

### ISSUE THREAD

**Issue by caioproiete** [continuousit/seq-releases#356]
I'd like to see the NuGet package ID of each app, when browsing the apps inside Seq.

It's hard to understand which packages are installed vs the packages available on NuGet.
e.g. How do I know that "**Formatted e-mail**" is "**Seq.App.Email**"?

![image](https://cloud.githubusercontent.com/assets/177608/11288856/a35c6d24-8efd-11e5-96ca-a02d052c2214.png)

**Comment by nblumhardt** [comment]
Great suggestion, thanks.

**Comment by nblumhardt** [comment]
Snuck this in via the _Manage_ link:

![image](https://cloud.githubusercontent.com/assets/342712/13623925/e2c99ca8-e5f5-11e5-9d09-3cfea9ceea67.png)

**Comment by caioproiete** [comment]
Sweet. Thanks!
