### ISSUE TITLE
Cannot write Verbose/Debug items to Seq, Log File, etc

### ISSUE THREAD

**Issue by KeithBarrows** [continuousit/seq-releases#357]
My startup code:
```
Log.Logger = new LoggerConfiguration()
    .WriteTo.ColoredConsole(
        outputTemplate: "{Timestamp:HH:mm} [{Level}] ({Name:l}) {Message}{NewLine}{Exception}")
    .WriteTo.Seq(
        ConfigSettingsWebApi.Instance.SeqUrl,
        restrictedToMinimumLevel: ConfigSettingsWebApi.Instance.SeqEventLevelValue,
        bufferBaseFilename: ConfigSettingsWebApi.Instance.SeqBufferPath)
    .WriteTo.RollingFile(
        ConfigSettingsWebApi.Instance.LogFile,
        restrictedToMinimumLevel: ConfigSettingsWebApi.Instance.LogFileEventLevelValue,
        retainedFileCountLimit: ConfigSettingsWebApi.Instance.LogCount)
    .Enrich.With(new HttpRequestClientHostIPEnricher())
    .Enrich.With(new HttpRequestIdEnricher())
    .Enrich.WithProperty("Environment", ConfigSettingsWebApi.Instance.EnvironmentName)
    .Enrich.WithProperty("Application", ConfigSettingsWebApi.Instance.ApplicationName)
    .CreateLogger();

Log.Debug("---==< Logging Started >==---");
Log.Debug("Environment: {val}", ConfigSettingsWebApi.Instance.EnvironmentName);
Log.Debug("Application: {val}", ConfigSettingsWebApi.Instance.ApplicationName);
Log.Debug("Logging to file: {fileName}", ConfigSettingsWebApi.Instance.LogFile);
Log.Debug("Logging level: {@logLevel}", ConfigSettingsWebApi.Instance.LogFileEventLevelValue);
Log.Debug("Logging to SEQ: {fileName}", ConfigSettingsWebApi.Instance.SeqUrl);
Log.Debug("Logging level: {@logLevel}", ConfigSettingsWebApi.Instance.SeqEventLevelValue);
```
My config:
```
<infoWebApiStartup authority="#########" requiredScopes="openid|profile|email|read|offline_access" loginAttemptsAllowed="3" logFile="C:\Logs\Auth\{Date}.log" logFileEventLevel="verbose" logCount="60" seqUrl="http://localhost:5341" seqEventLevel="verbose" seqBufferPath="C:\Logs\Auth" environmentName="Local Dev" applicationName="WebApi" />
```

None of these logged items show up in Seq or the log file.  I have no idea what might be wrong.

**Comment by nblumhardt** [comment]
Hi Keith - you'll need a `MinimumLevel.Debug()` or `MinimumLevel.Verbose()` in your logger configuration to enable these levels - the default is `Information`. Hope this helps!

**Comment by KeithBarrows** [comment]
'restrictedToMinimumLevel: ConfigSettingsWebApi.Instance.LogFileEventLevelValue,' where the config entry is set to Verbose.  There is no `minimumLevel` paramater available!  Or I am not finding it.

**Comment by KeithBarrows** [comment]
I think I found it.  Some of the (older) blog entries show MinimumLevel as a paramater to the sink setup.  It is not there (anymore?)  I found a MinimumLevel property on the LoggerConfiguration object.  That seems to have opened up what I can now log.

To confirm, the sink restrictedToMinimumLevel takes precedence, correct?

**Comment by nblumhardt** [comment]
Hi Keith - yes, that's the case. `MinimumLevel.X()` will set the level at which events will be generated, while `restrictedToMinimumLevel` is a filter applied later (hence the variation in the names). Glad you've got this one sorted, don't hesitate to reach out if we can help with anything else. Cheers!

**Comment by R3dByt3** [comment]
I could kinda reproduce this issue:
1. It would be nice if there would be some public API for setting the logging level statically; Currently there is only:
```
    public static ILoggingBuilder AddSeq(this ILoggingBuilder loggingBuilder, string serverUrl = "http://localhost:5341", string apiKey = null)
    {
        if (loggingBuilder == null)
        {
            throw new ArgumentNullException("loggingBuilder");
        }

        if (serverUrl == null)
        {
            throw new ArgumentNullException("serverUrl");
        }

        loggingBuilder.Services.AddSingleton((Func<IServiceProvider, ILoggerProvider>)((IServiceProvider s) => CreateProvider(s.GetService<ILoggerProviderConfiguration<SerilogLoggerProvider>>()?.Configuration, serverUrl, apiKey)));
        return loggingBuilder;
    }
```
But no overload like for ILoggerFactory:
```
    public static ILoggerFactory AddSeq(this ILoggerFactory loggerFactory, string serverUrl = "http://localhost:5341", string apiKey = null, LogLevel minimumLevel = LogLevel.Information, IDictionary<string, LogLevel> levelOverrides = null)
    {
        if (loggerFactory == null)
        {
            throw new ArgumentNullException("loggerFactory");
        }

        if (serverUrl == null)
        {
            throw new ArgumentNullException("serverUrl");
        }

        SerilogLoggerProvider provider = CreateProvider(serverUrl, apiKey, minimumLevel, levelOverrides);
        loggerFactory.AddProvider(provider);
        return loggerFactory;
    }
```
2. After seeing that I had to use the IConfigurationSection overload I switched to this approach, but sadly I had still no luck. So I was wondering what the issue might be and started debugging:
- While the rest of the configuration was working, I noticed that the minimum logging level was read and set correctly, but it was not used on any created logger. This could be fixed by prepending `loggingBuilder.SetMinimumLevel(LogLevel.Trace);`:
```
        _services.AddLogging(loggingBuilder =>
        {
            loggingBuilder.SetMinimumLevel(LogLevel.Trace);
            loggingBuilder.AddSeq(configuration.GetSection("Seq"));
        });
```

**Comment by nblumhardt** [comment]
Thanks for the notes @R3dByt3. This issue is discussing the Serilog/Seq integration, I think you're referring to https://github.com/datalust/seq-extensions-logging, though I think the essentials of the behavior you're describing in (2) are the same :+1:
