### ISSUE TITLE
Add to Chocolatey

### ISSUE THREAD

**Issue by AndreyUtka** [continuousit/seq-releases#36]
I think it would be great to create chocolatey package for seq.
It makes easier to manage and install it on servers (for example with boxstarter.org)

**Comment by nblumhardt** [comment]
Closing for now, it's still a nice idea but not likely to be tackled in the near future. I've moved it to: https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976135-chocolatey-installer-for-seq

Thanks!
