### ISSUE TITLE
Searching archive needs to show progress by date

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#369]
Currently an event count is shown, but this can be hard to map onto a date. Ideally Seq should show how far back in the stream is being searched.

**Comment by nblumhardt** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/342712/13205533/ed0087b2-d935-11e5-91b2-bf63d6159911.png)

**Comment by jansson** [comment]
This displays time in AM/PM format regardless of your settings around timestamps. And I freakin' hate AM/PM format ;-)

**Comment by nblumhardt** [comment]
@jansson thanks :-) https://github.com/continuousit/seq-releases/issues/396
