### ISSUE TITLE
Support UDP (without reload) view logs

### ISSUE THREAD

**Issue by AndreyUtka** [continuousit/seq-releases#37]
Whats about to support web sockets for udp view logs? I know that seq have opportunity to enable page reload, but it would be more convenient (for udp view) to receive logs with sockets.

**Comment by nblumhardt** [comment]
Thanks again for the suggestion/info. Now tracking via: https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976138-support-additional-input-channels-e-g-udp
