### ISSUE TITLE
Seq installer not checking .NET framework version

### ISSUE THREAD

**Issue by laurencee** [continuousit/seq-releases#371]
Installed Seq on a box which had an older version of .NET framework (I think it had 3.5). 
The install completed and we wanted to change the storage directory but the seq.exe tool can't be run on that box since that box does not have .NET 4.5 installed.

The installer should demand that .NET 4.5 is installed.

**Comment by nblumhardt** [comment]
Thank you for the note.

**Comment by nblumhardt** [comment]
Done; though we recommend .NET 4.6 or later, the installer will accept 4.5.2 or later.
