### ISSUE TITLE
Allow setting listen url and storage path during installation

### ISSUE THREAD

**Issue by laurencee** [continuousit/seq-releases#372]
When installing Seq the most common things to configure are the listen and storage paths. 

It would be preferable to have these configurable both in the installer UI and through command line installation of the msi. The latter is less important since it's not like you install Seq all over the place but it would help with automated deployment.

**Comment by nblumhardt** [comment]
Thanks for the suggestion Laurence, definitely something we'd like to do in the near future :+1:

**Comment by nblumhardt** [comment]
BTW, though the name is terrible, I believe today you can do:

```
msiexec /I Seq-3.0.30.msi WIXUI_EXITDIALOGOPTIONALCHECKBOX=0
```

to disable the default post-installation config, then run:

```
seq.exe install --listen=http://xyz --storage=A:\B\C
```

to configure these options.

In 3.1 we'll add both to the post-install UI, not sure that will improve this scenario however.

**Comment by nblumhardt** [comment]
GUI configuration for 3.1 is done.

![image](https://cloud.githubusercontent.com/assets/342712/14133757/5526b0b0-f695-11e5-845a-2b267d7e7d3d.png)

Between the user interface and command line options above I think we've now got all bases covered. Please let me know if you think there are still gaps - thanks!
