### ISSUE TITLE
Seq queries on EventType : int vs hex vs string ?

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#373]
Hi,

I am trying to use the new "sql-like" queries to get some stats on the most generated "types of events" and then filter on the EventType.

When using "normal" signals, EventType appears with a `$` prefix, and can be used to filter without any special operators: 
![seq-eventtype](https://cloud.githubusercontent.com/assets/160544/13313168/2e743d52-db9c-11e5-88c5-28e153dc7983.png)

if I try to apply the same kind of filters in the "sql-like" queries, I kind of struggle ...

I tried : 
- `select * from stream where @EventType="$63D88CE9"`
  
  returns *Syntax error (col 39): unexpected '"', expected -, not or expression.*
- `select * from stream where $63D88CE9`

  returns *Syntax error (col 28): unexpected '$', expected where clause predicate.*
- `select * from stream where  @EventType="63D88CE9"`

  returns *Syntax error (col 40): unexpected '"', expected -, not or expression.*

If I execute `select * from stream` I can see the *EventType* column with values `0x...` that kind of looks like the event-type I need.. so then I can try 

- `select * from stream where @EventType= 0x63d88ce9`

  this returns *Syntax error (col 41): unexpected 'x'.*

From the [blog post](http://blog.getseq.net/seq-3-0-21-pre-sql-improvements-ux-tweaks/), I see that the default `select * from stream` shows `ToHexString(@EventType)` so I deduce that this should work : 
- `select * from stream where ToHexString(@EventType)="0x63d88ce9"`

  but this returns *Syntax error (col 52): unexpected '"', expected -, not or expression.*

So anyway, my question is : 
**How can I filter by event-type ?** 

Thanks in advance, and keep up the good work :)

(as of Seq 3.0.21-pre)

**Comment by nblumhardt** [comment]
Hi Thibaud,

The last option you tried is correct apart from the need for single-quoted strings in SQL:

```sql
select * from stream where ToHexString(@EventType) = '0x63d88ce9'
```

But, it is of course very inefficient :-)

Earlier builds of 3.0 supported the `$12345678` syntax in SQL, but it was pulled in the recent preview (along with support for C#-style strings in SQL) in an effort to reign in all the variations in syntax.

The intention is to enable this syntax in the next preview:

```sql
select * from stream where @EventType = 0x63d88ce9
```

Although hex literals in standard SQL are `x'12345678'` the `0x` syntax is widely supported also and is a bit easier on my eyes.

Under the hood, equality comparisons against `@EventType` will be handled in the same way as the `$` syntax supports now.

(I'm interested in your thoughts on this. I'd initially tried to meld SQL and Seq's current filter syntax into a more consistent language but felt it was becoming an ad-hoc monster, so the newer release's adherence to "real" SQL is taking the opposite approach.)

**Comment by tsimbalar** [comment]
Oh ok, that makes sense :)

As a user, I kind of expect the 2 different syntaxes to work, but as a developer, I understand that you want the sql-like syntax to remain close to "standard" sql.

Maybe a good middleground would be to detect when a user types in the "where" clause some syntax that looks valid for Seq signals but is not valid in Sql, and show a helpful error message ... and maybe suggestions to fix it

Some things I can think about : 
- single-quote vs double-quoted strings : `select * from stream where @Message like "Response%"` ... a message could say "did you mean ... `select * from stream where @Message like 'Response%'` 
- C# like operators : `&&` , `||` , `==` -> explicitely say "the C#syntax is not supported here, use `and` `or` etc"
- special Seq syntax : `$EventType` : if you see I use the `$` sign, say that we might be trying to filter on the `@EventType` and it's better to use another syntax ... ideally show what the syntax would be like

Also, maybe the docs should be a bit more explicit about the fact that the [filter syntax](http://docs.getseq.net/docs/query-syntax) can not be copy-pasted directly inside a [Sql query](http://docs.getseq.net/docs/sql-queries)

Any way, all that stuff may not need to be in 3.0.0 , but, who doesn't like helpful error messages ? ;)

**Comment by nblumhardt** [comment]
Love it! Not perfect, but coming in the next preview:

![image](https://cloud.githubusercontent.com/assets/342712/13370078/1e420b8a-dd4a-11e5-92ed-b2cd75397bf8.png)

**Comment by tsimbalar** [comment]
:sunglasses:

**Comment by tsimbalar** [comment]
It's just cosmetics, but maybe putting the suggestions out of the big red block would make the error less overwhelming ... 
I would probably leave the "technical error" in read, but put the "friendlier" message in a less aggressive color : 

![seq-error-messages](https://cloud.githubusercontent.com/assets/160544/13388951/945f6bfc-dec4-11e5-8872-796dd2d5bc33.png)

(probably not the best choice of colors and fonts, but you get the idea :P )

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/13420021/62123e94-dfce-11e5-943c-7d4376d3b0f6.png)

(Slight tweak, still more improvements possible but a bit better; with the "help" link in the menu bar I think the extra link was redundant)

**Comment by tsimbalar** [comment]
:+1:
