### ISSUE TITLE
Missing Tooltips

### ISSUE THREAD

**Issue by Mike-EEE** [continuousit/seq-releases#374]
First off... THIS IS SUCH AN AWESOME PRODUCT!!! :smile: 

Very well-done and incredibly easy to use!  It JUST WORKS without having to do anything but INSTALL IT.  This is coming from someone who has spent WEEKS enduring the pain of learning ETW and SLAB and allllllll the pain that came with it.

THIS IS SO MUCH BETTER AND SHOULD BE THE GOLD -- nay, DIAMOND! PLATINUM!!! -- standard for all .NET projects! :smile: :smile: :smile: 

Ok ok... so with all of the praise out of the way, I did find something that needs some love, especially for newbs like me who are learning it for the first time.

It would be great to see tooltips for the controls in the webapp UI:

![](http://content.screencast.com/users/Mike-EEEE/folders/Jing/media/06372e13-53b5-4c5c-8a32-cc416e0854bb/2016-02-26_1540.png)

Thank you for any consideration!

**Comment by nblumhardt** [comment]
Fixed, thanks Michael!

![image](https://cloud.githubusercontent.com/assets/342712/13382414/c39a4f68-debf-11e5-8b9c-789083fb2f44.png)

They read: _Refresh_, _Auto-refresh_ and _Add the current filter to a Signal_.
