### ISSUE TITLE
Seq.json

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#376]
In Seq 2, all parameters to `seq install` must be called every time it's called. This is error-prone when, for example, data needs to be moved to another location.

It's subsequently difficult to verify what these are, because they're only stored in the service executable's arguments.

In Seq 3 we'll persist settings in a new file, _Seq.json_ instead:

```
seq install --listen="https://my-seq"
```

Seq.json:

```json
{
  "api": {
    "listenUris": [
      "https://my-seq/prd"
    ]
  },
  ...
}
```

...later:

```
seq uninstall
seq install
```

Parameters not specified on the subsequent `install` command will be unmodified.

**Comment by nblumhardt** [comment]
Done.

**Comment by IanYates** [comment]
:100: - I find I either need to move files or adjust the RAM limit.  This will make that process less fraught.  Thanks!

**Comment by nblumhardt** [comment]
:+1:
