### ISSUE TITLE
seq's bufferBaseFileName does not work from AppSettings

### ISSUE THREAD

**Issue by Thdm1907** [continuousit/seq-releases#389]
I am testing out the library and I cannot get the bufferBaseFileName to work with Seq from AppSettings. 
This is the code to test logging:
```
Log.Logger = new LoggerConfiguration()
                .ReadFrom.AppSettings()
                .CreateLogger();

Log.Logger.Debug("testing Debug");
Log.Logger.Verbose("testing Verbose");
Log.Logger.Information("testing Information");
Log.Logger.Warning("testing Warning");
Log.Logger.Error("testing Error");
Log.Logger.Fatal("testing Fatal");
```
In the app.config, I have just the following in the appSettings section:

```
  <add key="serilog:using" value="Serilog.Sinks.Seq" />
  <add key="serilog:write-to:Seq.serverUrl" value="http://MyIP:5341/" />
  <add key="serilog.write-to:Seq.bufferBaseFilename" value="C:\MyLogs\Buffer" />
```
With the Seq server not running, there is no file created in the C:\MyLogs\ folder. If Seq is configured through code, there are .bookmarks and .json files in C:\MyLogs folder.
```
Log.Logger = new LoggerConfiguration()
     .WriteTo.Seq("http://MyIP:5341", bufferBaseFilename: @"C:\MyLogs\Buffer")
     .CreateLogger();
```
 The build I'm using is 1.5.14.

**Comment by nblumhardt** [comment]
Thanks for the report - I've reproduced this, trying to get to the bottom of it now...

**Comment by nblumhardt** [comment]
Ah - sorry, my eyes failed me on this one. In the third directive, you've got `serilog.write-to` instead of `serilog:write-to`. Note the `:` :-) ... Easy typo to make!

Hope this fixes it - works for me.

Regards,
Nick

**Comment by Thdm1907** [comment]
Thanks for the catch. It works as expected now. 
I wonder if there is a feature request for retaining multiple log files per day for RollingFile sink, and perhaps it applies to Seq's bufferBaseFileName feature also. I don't see how it can be done right now since the log file name only contains the date. So instead of having one log file per day (which can be too big to open), there can be up to "retainedFileCountLimit" files that span multiple days. This is a feature that I love from Enterprise Logging. If there's a way to achieve this, I'd like to know. If not, it would be a good feature to add.

**Comment by nblumhardt** [comment]
Thanks for the follow-up, glad to hear it's sorted out.

There's a size-based rolling file implementation here: https://github.com/BedeGaming/sinks-rollingfile - interested to hear if it fits what you're looking for.
