### ISSUE TITLE
Add some commonly-used aggregates to the quick-filter list

### ISSUE THREAD

**Issue by nblumhardt** [continuousit/seq-releases#404]

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/14417249/3c39571e-fff6-11e5-8ddd-a1195b92cd1c.png)

 * **Count by value** - selects count grouping by the value
 * **Plot over time** - selects timestamp and value where the value is not null
 * **Plot aggregates...* - min, max, mean, c95th by one hour intervals

**Comment by tsimbalar** [comment]
I was going to request exactly that :)
