### ISSUE TITLE
"help" link brings to docs v2

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#405]
... it should bring to the latest and greatest (or at least the version we have installed).

Running Seq 3.1.10-pre, if I click the "help" link in the top nav bar, I end up on http://docs.getseq.net/v2/docs/query-syntax  ... And from here, if I click "Sql Queries" I get : 

>  Coming in Seq 3
> 
> SQL Queries are a new feature in Seq 3. You can download an early preview build from the Seq downloads page.

I understand that v3 is no longer in preview, so the active docs should be v3.

I believe there is a "canonical" help URL at https://getseq.net/help with a wrong redirection.

**Comment by nblumhardt** [comment]
Thank you Thibaud! The whole idea of the canonical URL was to avoid broken documentation links... #fail :-|

Fixed now :-)
