### ISSUE TITLE
Add filter/search history drop down for quick history

### ISSUE THREAD

**Issue by slimflem** [continuousit/seq-releases#60]
It would be super awesome to have some level of filtering and search history available in a drop down such as:

![image](https://f.cloud.github.com/assets/886340/2053608/747f9016-8aaa-11e3-8408-12a68ddf6eb7.png)

I think at least your last 10 - 15 filters/searches would be a good start.

**Comment by nblumhardt** [comment]
I think this one is too big to track as a ticket - more a roadmap item; closing to get the issue tracker down to a manageable size, but not forgotten. Thanks Jesse!

**Comment by nblumhardt** [comment]
Added: https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976174-extended-search-bar
