### ISSUE TITLE
Replication between Seq instances

### ISSUE THREAD

**Issue by slimflem** [continuousit/seq-releases#61]
I'll go ahead and make an official request for this for Enterprise licensing.

It would be a worthwhile feature to invest in realizing this is not a trivial feature at all.

**Comment by nblumhardt** [comment]
Switched to durable replication recently; currently "more" is on the roadmap but not in the immediate future. Just trimming back the tracker so please feel free to comment/re-open or add a suggestion to http://seq.uservoice.com as needed. Thanks!
