### ISSUE TITLE
Enhanced search bar with autocomplete

### ISSUE THREAD

**Issue by arri-cc** [continuousit/seq-releases#93]
Albeit quite ambitious, it would be extremely useful if the search feature supported autocomplete based on the contents of existing logs. The best working example is YouTrack's search bar:
http://www.youtube.com/watch?v=fzkKcG7KIhI

This would be an amazing feature similar to what's currently available via other logging platforms like graylog2.

**Comment by nblumhardt** [comment]
Still an awesome idea; moving it to https://seq.uservoice.com/admin/forums/268188-general/suggestions/6976174-extended-search-bar
